### ISSUE TITLE
Doesn't work with extra spacing

### ISSUE THREAD

**Issue by dwelle** [dzhavat/css-initial-value#1]
For colon-aligned styleguides, it seems it doesn't work:

```css
.test {
   height: 10px;
   width : 10px; /* <--- hover doesn't work here */
}
```

Should be an [easy fix](https://github.com/dzhavat/css-initial-value/blob/master/src/extension.ts#L24).
